# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/AIOT/SoC/0429/Create_memory/Create_memory.srcs/sources_1/ip/spram2/spram2.xci
# IP: The module: 'spram2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/AIOT/SoC/0429/Create_memory/Create_memory.gen/sources_1/ip/spram2/spram2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spram2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/AIOT/SoC/0429/Create_memory/Create_memory.srcs/sources_1/ip/spram2/spram2.xci
# IP: The module: 'spram2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/AIOT/SoC/0429/Create_memory/Create_memory.gen/sources_1/ip/spram2/spram2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spram2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
