.ALIASES
R_R1            R1(1=EI 2=N01215 ) CN @DDD.SCHEMATIC1(sch_1):INS1050@ANALOG.R.Normal(chips)
R_R2            R2(1=N01215 2=0 ) CN @DDD.SCHEMATIC1(sch_1):INS1066@ANALOG.R.Normal(chips)
L_L1            L1(1=EI 2=N01257 ) CN @DDD.SCHEMATIC1(sch_1):INS1120@ANALOG.L.Normal(chips)
R_R3            R3(1=N01257 2=0 ) CN @DDD.SCHEMATIC1(sch_1):INS1145@ANALOG.R.Normal(chips)
C_C1            C1(1=EI 2=N01270 ) CN @DDD.SCHEMATIC1(sch_1):INS1170@ANALOG.C.Normal(chips)
R_R4            R4(1=N01270 2=0 ) CN @DDD.SCHEMATIC1(sch_1):INS1195@ANALOG.R.Normal(chips)
V_V1            V1(+=EI -=0 ) CN @DDD.SCHEMATIC1(sch_1):INS1750@SOURCE.VSIN.Normal(chips)
_    _(ei=EI)
.ENDALIASES
